language: generic 
sudo: required 
services :
  - docker 
before_install:
  - docker build -t mohamedbenkhemis/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true mohamedbenkhemis/docker-react npm run test
